class BMW:
    def price(price):
        print("rs.10000000")
        
    def color(color):
        print("black")
        
    def year (year):
        print("2089")    
        
class ferrari:
    def price(price):
        print("Rs.10000000")
        
    def color(color):
        print("blue")
        
    def year (year):
        print("2039")
        
b=BMW()
f=ferrari()
for i in  (b,f):
     i.price()
     i.color()
     i.year()
         
     
                   